compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableTelemetry: false

nodeLinker: node-modules

# for changing use `yarn set version --yarn-path 4.9.4`
yarnPath: .yarn/releases/yarn-4.9.4.cjs
