#!/bin/bash
#
# Copyright (c) 2025 Ronan Le Meillat - SCTG Development
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ ! -n "$PROJECT_ROOT" ]; then
    echo "If you restore for a cloned repo you may declare a PROJECT_ROOT environment variable before running this"
    exit 0
fi
echo "PROJECT_ROOT is set to '$PROJECT_ROOT'"
read -p "Press any key to continue... " -n1 -s
PWD=`pwd`
cd ~
#1-decrypt
DECRYPT=""
if [ -n "$CRYPTOKEN" ]; then
    DECRYPT="-pass pass:$CRYPTOKEN"
    echo "Decrypting with 'openssl aes-256-cbc -a -d -md sha256 $DECRYPT -in $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz.enc -out $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz'"
else
    DECRYPT=""
fi
openssl aes-256-cbc -a -d -md sha256 $DECRYPT -in $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz.enc -out $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz
#2-show content
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "_sensitive_datas/_sensitive_datas.tar.xz contains:"
tar -tvJf $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz
#3 show help
echo "if you want to restore enter:"
echo "cd $PROJECT_ROOT && tar -xvJf $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz && rm $PROJECT_ROOT/_sensitive_datas/_sensitive_datas.tar.xz"